version: "2"

services:
  neo4j:
    image: neo4j:4.1.2-enterprise
    networks:
      - host
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/zeppelin
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]

  zeppelin:
    image: apache/zeppelin:0.9.0
    networks:
      - host
    ports:
      - 8080:8080
    # environment:
    #   - ZEPPELIN_NOTEBOOK_HOMESCREEN=2FQE7PGXG
    #   - ZEPPELIN_NOTEBOOK_HOMESCREEN_HIDE=true
    volumes:
      - ./zeppelin/notebook:/zeppelin/notebook
      - ./zeppelin/conf:/zeppelin/conf
      - ./zeppelin/data:/zeppelin/data
      - ./zeppelin/jars:/jars
      - ./zeppelin/interpreter/neo4j:/zeppelin/interpreter/neo4j

networks:
  host:
